#:import Window kivy.core.window.Window
#:import _ i18n._

<LoginScreen>:
    canvas.before:
        Rectangle:
            texture: root.gradient_texture
            pos: self.pos
            size: self.size
    MDCard:
        pos_hint: {"center_x": .5,"center_y": .5}
        size_hint_x: 0.35
        size_hint_y: 0.92
    MDIconButton:
        icon: "translate"
        pos_hint: {"center_x": .36, "center_y": .89}
        id: language_button
        on_release: root.open_language_menu()
    MDIconButton:
        icon: "theme-light-dark"
        pos_hint: {"center_x": .64, "center_y": .89}
        on_release: app.toggle_theme()

    MDBoxLayout:

        orientation: 'vertical'
        spacing: '20dp'
        padding: '40dp'

        MDLabel:
            text: "FluentSound"
            halign: "center"

            font_style: "H4"
            theme_text_color: "Primary"

        MDLabel:
            id: error_label
            text: ""
            halign: "center"
            theme_text_color: "Error"
            size_hint_y: None
            height: self.texture_size[1]



        CustomTextField:
            hint_text: _("username_hint")
            icon_left: "account"

            id: username_field
            size_hint_x: 0.2
            pos_hint: {"center_x": .5}

        CustomTextField:
            hint_text: _("password_hint")
            password: True
            icon_left: "key-variant"

            id: password_field
            size_hint_x: 0.2
            pos_hint: {"center_x": .5}

        MDRaisedButton:
            id: Login_button
            text: _("Login_button")
            pos_hint: {"center_x": .5}
            on_release: root.process_login(username_field.text, password_field.text)

<HomeScreen>:
    canvas.before:
        Rectangle:
            texture: root.gradient_texture
            pos: self.pos
            size: self.size
    MDCard:
        pos_hint: {"center_x": .5,"center_y": .5}
        size_hint_x: 0.99
        size_hint_y: 0.98

    MDNavigationLayout:
        ScreenManager:
            Screen:

                MDLabel:
                    text: "WIP"
                    halign: "center"

        MDNavigationDrawer:
            id: homepage_menu
            state: "close"
            anchor: "left"
            MDCard:
                id: drawer_footer
                pos_hint: {"center_x": .5,"center_y": 0.03}
                size_hint_y: None
                size_hint_x: 1
                height: '56dp'
                md_bg_color: 0, 0, 0, 0.4
                FloatLayout:
                    MDIconButton:
                        icon: "theme-light-dark"
                        pos_hint: {"center_x": 0.9, "center_y": .5}
                        on_release: app.toggle_theme()
                    MDIconButton:
                        icon: "translate"
                        pos_hint: {"center_x": .75, "center_y": .5}
                        id: language_button
                        on_release: root.open_language_menu()
